### ISSUE TITLE
Programm funktioniert nicht

### ISSUE THREAD

**Issue by Schwimmerl** [resteqs/schluesselSpiel#2]
Das Programm an sich hat einen Fehler, der es einem nicht erlaubt, es zu auszuführen.

**Comment by niko314** [comment]
Hast du den WindowBuilder installiert?

**Comment by niko314** [comment]
Wenn nein gehe unter Eclipse zu Help -> install New Software.
Füge in der obersten Zeile diesen link ein: https://download.eclipse.org/windowbuilder/latest/.
Wenn du auf den Link klickst kommst du auch zur website die dir erklärt wie du den Windowbuilder installierst.

**Comment by Gochlfisch** [comment]
Ne, funktioniert immer noch nicht. Also entweder bin ich fett oder da ist irgend ein fehler drin

**Comment by niko314** [comment]
Schick mal die Fehlermeldung rein die du bekommst. Ich habe nämlich keine.

**Comment by Gochlfisch** [comment]
Exception in thread "main" java.lang.Error: Unresolved compilation problem: 
	BildschirmFenster cannot be resolved

	at MainClass.main(MainClass.java:6)

Also wie gesagt vielleicht bin ich auch dumm

**Comment by Gochlfisch** [comment]
Führe ich nur Bildschirmfenster aus, kommt sowas wie "Unable to find ANT file"

**Comment by niko314** [comment]
Schickt mal ein Bild von Ecplise am Rand wo alle Klassen/Files stehen. Bei mir Funktioniert halt alles.

**Comment by resteqs** [comment]
Also das Programm funktioniert safe. Habt ihr noch Probleme? Ansonsten würde ich schließen.

**Comment by Gochlfisch** [comment]
ne, geht immer noch nicht, ist aber egal
