### ISSUE TITLE
Graphik flackert

### ISSUE THREAD

**Issue by resteqs** [resteqs/schluesselSpiel#4]
Bei mir flackert alles die ganze Zeit. Die die Graphik implementiert haben sollten sich darum kümmern. Schreibt mir wenn ihr ned wisst was ich meine

**Comment by niko314** [comment]
Liegt daran, dass wenn sich bei uns ein Bildobjekt bewegt, alle Element einzeln neu auf den Screen "gemalt" werden. Stattdessen sollten wir jedesmal wenn sich ein Bildelement ändert alle Elemente zu einem Gesamtbild hinzufügen und dann erst dem aktuell angezeigten Bild überschreiben. Nennt sich Double buffering. Um mehr darüber sagen zu können muss ich mich aber erstmal ein bisschen in die Dokumentationen einlesen.

**Comment by soccergrl5** [comment]
Mir ist das Problem bekannt, und ich arbeite auch bereits an einer Lösung. Wie Nikolai sagt brauchen wir DoubleBuffering um das zu lösen. Allerdings hatte ich heute erstmal die Text Klasse gemacht, sodass es erstmal was gibt, was auf dem Fenster steht.

**Comment by resteqs** [comment]
Wenn das Problem "bekannt" ist warum macht ihr dann kein Issue 🤔
Aber gut, dass ihr an einer Lösung arbeitet

**Comment by soccergrl5** [comment]
Wusste nicht, dass ich deswegen eins erstellen soll 😅

**Comment by soccergrl5** [comment]
Also es sollte jetzt funktionieren

**Comment by niko314** [comment]
Funktioniert
