### ISSUE TITLE
Buttons brauchen Eventsystem und nicht Observer-Pattern

### ISSUE THREAD

**Issue by niko314** [resteqs/schluesselSpiel#5]

**Comment by niko314** [comment]
Nach Klassendiagramm sind die Buttons mit einem Event-System verbunden. Bei diesem Lösen sie ein bestimmtes Event aus wenn sie geklickt werden. Beim Button "Spiel Starten" würde der jeweilige Button dem EventSystem sagen, dass das Spiel gestartet werden soll und das EventSystem informiert dann z.B den Gamemanager darüber.

**Comment by Snifelon17** [comment]
Ich weiß das das im Klassendiagramm anders drin steht aber es is ist so viel schöner. Wenn man das über eine Klasse EventSystem machen würde breuchte man in der lauter if funktionen die abfragen welcher button gedrückt wurde. Mit dem observer ist es besser, weil da muss ein Observer nur knöpfe abfragen die er auch  selber erstellt hat.
Wenn du noch ne andere Lösung hast oder glaubst das Herr Leebmann abweichungen vom Klassendiagramm hasst (Von mir auß kann ich des auch nochmal anpassen), kann ich des noch ändern, aber wenn man es gescheid begründet glaube ich nicht das er es so schlimm findet.

**Comment by niko314** [comment]
Bitte ändere es zu einem EventSystem. Observer-Pattern ist falls sich die Elemente die Informiert werden sollen ständig ändern können. Hier steht es aber fest. Sonst hast du auch dass Problem, dass jedes Element, dass informiert werden soll erst mal eine Referenz zu dem Button braucht und sich "eintragen" muss. Dass beim EventSystem lauter if abfragen sind ist ok. Kannst ja wenn du es schöner findest auch Switch-Case anwenden. Ist insgesamt sauberer weil man dann beim EventSystem direkt sehen kann, was passiert wenn ein bestimmtes Event ausgelöst wird und einfach Änderungen vornehmen kann. Hab ich mit Herr Leebmann beim erstellen des Klassendiagramms auch so besprochen.

**Comment by Snifelon17** [comment]
Okay wenn du des mit Herr Leebmann abgesprochen hast ändere ich des noch.
