### ISSUE TITLE
Nach dem Pausieren wird der Timer resetet und nicht pausiert

### ISSUE THREAD

**Issue by resteqs** [resteqs/schluesselSpiel#6]

**Comment by resteqs** [comment]
@Gochlfisch die Funktion timer.stop() resetet auch den Stopwatch. Wofür gibt es dann Timer Reset? Kannst du eine Methode erstellen die den Timer pausiert, ohne, dass der aktuelle Stand gelöscht wird?

**Comment by Gochlfisch** [comment]
Bin grad schon dran

**Comment by resteqs** [comment]
Kuss

**Comment by Gochlfisch** [comment]
Finished
