### ISSUE TITLE
Buttons werden beim Pausieren nicht richtig angezeigt

### ISSUE THREAD

**Issue by soccergrl5** [resteqs/schluesselSpiel#7]
Wenn das Spiel pausiert wird, wird zwar der Hintergrund angezeigt, die Buttons aber erst, wenn man mit der Maus drüberhovert. Ich gehe mal davon aus, dass das bei den anderen Menüs nicht anders ist. Will des vielleicht wer machen, der sich besser mit den Buttons auskennt?

**Comment by niko314** [comment]
Ich weiß woran es liegt. Fixe es gleich.
